### ISSUE TITLE
Search results are showing categories that are NOT included in the navigation

### ISSUE THREAD

**Issue by byersdesign** [algolia/algoliasearch-magento#312]
It seems that search results are showing categories that are hidden from the navigation. So, for example: Categories that were never meant to be found by customers just viewing the website are now finding them. These might include categories that are used from promotional purposes.

**Comment by byersdesign** [comment]
For example, if you search for "Offer" here: https://www.littlewomen.com

**Comment by maxiloc** [comment]
This got fixed with https://github.com/algolia/algoliasearch-magento/commit/d7c01b74a1277eeabf0676d7a26fe39814ec113d

It will be part of this week release

**Comment by byersdesign** [comment]
So sorry to be a pain. I know you are probably a really busy guy and have lots of other bits to get on with but I have implemented the code changes mentioned in the 'd7c01b7' commit but its still pulling these categories into the autocomplete. I have re-indexed the results in Magento and checked on Algolia's dashboard. The "promotional" categories are still showing.

**Comment by maxiloc** [comment]
Yes you might need to clear the index first and then reindex

**Comment by byersdesign** [comment]
How would I clear the index first. Do you mean index Magento's indexes first and then run Algolia's ones?
I have done the following:

1. Run Magento's indexs'
2. Run Algolia's indexes'
3. Cleared cache
4. Run indexes again
5. Checked Algolia.com indices. they have updated but the promotional categories are still in there.

**Comment by maxiloc** [comment]
You need to go to Algolia dashboard find the category index, clear it. And the run the algolia search indexer.

**Comment by byersdesign** [comment]
You are so BOSS! Thank you Maxiloc

**Comment by lazyguru** [comment]
@maxiloc clearing the index in Algolia is not an option for merchants with +500 products.  It takes 4-6 hours for a full reindex.  They can't have their site completely down during that time.  How can they get this update without clearing the index?

**Comment by maxiloc** [comment]
@lazyguru This is for the category index which should not be more than few hundred records in the worse case scenario

**Comment by spiralmedia-rupert** [comment]
I am finding that this is now an issue in version 1.6.1. Can you confirm this is not working for you?

**Comment by spiralmedia-rupert** [comment]
@maxiloc

**Comment by JanPetr** [comment]
Hey @spiralmedia-rupert,
I cannot reproduce on 1.6.1.

Can you take a look into your categories index and see if those categories have attribute `include_in_menu` set to `0`? And can you please provide live example? Thank you!

**Comment by spiralmedia-rupert** [comment]
Hey @JanPetr 

Here is a screenshot from Algolia dashboard. I have changed url (via developer tools) for but all the other data is correct.

![screen shot 2016-09-07 at 14 57 18](https://cloud.githubusercontent.com/assets/3028655/18314561/7a346f4c-750b-11e6-8d71-55d0fc02cee1.png)

**Comment by JanPetr** [comment]
Thanks @spiralmedia-rupert, it looks correct.
I suppose you have this setting set to No as well, right?
<img width="933" alt="screenshot 2016-09-07 16 00 46" src="https://cloud.githubusercontent.com/assets/1058144/18314690/69d662d2-7514-11e6-84a3-38ae565c7d46.png">

Can you please share the live website? If you don't want to share it publicly you can send it to support@algolia.com

Thank you

**Comment by spiralmedia-rupert** [comment]
Ahh, what a noob. Just updated to version 1.6.1 and this must be a new option. Thank you so much. Life saver.

**Comment by JanPetr** [comment]
No problem :) Glad I could help!
