### ISSUE TITLE
Wrong character in suggestion search

### ISSUE THREAD

**Issue by trinhluong** [algolia/algoliasearch-magento#540]
I have install lastest version of your extension.
when I re-index and doing with search it show wrong display
![algolia parse template error](https://cloud.githubusercontent.com/assets/10395684/17541075/2f79fd9a-5ee6-11e6-953e-b931f25bbbc1.png)
how to fix it, please

**Comment by JanPetr** [comment]
Hello @trinhluong,
by the latest you mean 1.6.1? Did you do any changes to templates? Do you have any errors in your console?

**Comment by trinhluong** [comment]
@JanPetr I dont change anything. And it is no errors in console.
On my local it work fine. but when I move to server it wrong like my report.

**Comment by trinhluong** [comment]
Current php version is 5.6 @JanPetr

**Comment by JanPetr** [comment]
Weird, I'm not able to reproduce.
Did you flushed all caches after updating the extension?

The only lines from where it can come from are [here](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/autocomplete.phtml#L33) and [here](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/autocomplete.phtml#L130). It seems like your browser has issues with interpreding `CDATA` tags. Can you try to remove it temporarily?
Do you have any public website where I could try it?

**Comment by trinhluong** [comment]
I already clear all caches. So let me try remove CDATA.
Sorry my website is not public, mate
Thanks

**Comment by trinhluong** [comment]
@JanPetr 
I pushed into server
can you check with me. please add hosts 52.62.84.130  www.pushys.com.au

and go to pushys.com.au with browser to check

**Comment by JanPetr** [comment]
I did but the server is unreachable:
![screenshot 2016-08-10 11 00 13](https://cloud.githubusercontent.com/assets/1058144/17547914/a9612a68-5ee9-11e6-9072-89d0fdb66bd6.png)

Did you remove `CDATA` tags? Does the issue persist?

**Comment by trinhluong** [comment]
I removed but it still error.
please change host to 
52.64.222.43  www.pushys.com.au

**Comment by JanPetr** [comment]
OK, I tried and I can see that `CDATA` tags are present in JS templates template of autocomplete menu. For example:
<img width="606" alt="screenshot 2016-08-10 11 27 41" src="https://cloud.githubusercontent.com/assets/1058144/17548734/81764476-5eed-11e6-98d7-0e8574921875.png">

But in extension files, there are no `CDATA` tags at all. You can take a look in [product template](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/autocomplete/product.phtml#L18-L19) for example.

It seems like your are using some code minifier on your production site which might add `CDATA` tags into those templates. You'll have to investigate on your side how the `CDATA` tags appear ar your code.

**Comment by trinhluong** [comment]
Thank you so much @JanPetr 
I got it. and now I fix it now.

**Comment by JanPetr** [comment]
Glad I could help ;)
